

// Top trader data structure
export interface TopTrader {
    rank: number;
    username: string;
    avatar: string;
    flag: string;
    badge: string | null;
    wins: number;
    winsChange: string | null;
    winsUp: boolean | null;
    rekts: number;
    rektsChange: string | null;
    rektsUp: boolean | null;
    challenges: number;
    winRate: string;
    earnings: string;
    isTop: boolean;
}

// Placeholder challenges for market page
export const PLACEHOLDER_CHALLENGES: any[] = [
    {
        id: "placeholder-1",
        status: "open",
        asset: "BTC",
        creator_wallet: "placeholder-wallet-1",
        challenge_type: "price_up",
        amount: "100",
        expires_at: Date.now() + 86400000,
        created_at: Date.now(),
        description: "Bitcoin price prediction challenge",
        assetLogo: "/scribbles/btc.png",
        title: "BTC Price Challenge",
        creator: {
            name: "Anonymous",
            avatar: "/scribbles/pepe.png",
        },
        betAmount: 100,
        prediction: "Price will go up",
        currentPrice: 0,
        priceChange: 0,
        targetPrice: 0,
        startPrice: 0,
        timeRemaining: "24h",
        likes: 0,
        mode: "pvp",
        challengerCount: 1,
        defenderCount: 0,
        totalPool: 100,
    },
    {
        id: "placeholder-2",
        status: "open",
        asset: "SOL",
        creator_wallet: "placeholder-wallet-2",
        challenge_type: "price_down",
        amount: "50",
        expires_at: Date.now() + 172800000,
        created_at: Date.now(),
        description: "Solana price prediction challenge",
        assetLogo: "/scribbles/sol.png",
        title: "SOL Price Challenge",
        creator: {
            name: "TraderX",
            avatar: "/scribbles/sol.png",
        },
        betAmount: 50,
        prediction: "Price will go down",
        currentPrice: 0,
        priceChange: 0,
        targetPrice: 0,
        startPrice: 0,
        timeRemaining: "48h",
        likes: 0,
        mode: "pvp",
        challengerCount: 1,
        defenderCount: 0,
        totalPool: 50,
    },
];

// Top traders data
export const topTradersData: TopTrader[] = [
    {
        rank: 1,
        username: "DegenLord",
        avatar: "/scribbles/pepe.png",
        flag: "🇨🇦",
        badge: "C",
        wins: 178,
        winsChange: "+14",
        winsUp: true,
        rekts: 45,
        rektsChange: "-8",
        rektsUp: false,
        challenges: 325,
        winRate: "79%",
        earnings: "128.4 SOL",
        isTop: true,
    },
    {
        rank: 2,
        username: "TraderX",
        avatar: "/scribbles/btc.png",
        flag: "🇺🇸",
        badge: null,
        wins: 160,
        winsChange: null,
        winsUp: null,
        rekts: 68,
        rektsChange: "-7",
        rektsUp: false,
        challenges: 302,
        winRate: "81%",
        earnings: "116.2 SOL",
        isTop: false,
    },
    {
        rank: 3,
        username: "CryptoNinja",
        avatar: "/scribbles/shiba.png",
        flag: "🇰🇷",
        badge: null,
        wins: 150,
        winsChange: null,
        winsUp: null,
        rekts: 79,
        rektsChange: "-6",
        rektsUp: false,
        challenges: 315,
        winRate: "82%",
        earnings: "105.6 SOL",
        isTop: false,
    },
    {
        rank: 4,
        username: "MoonMaster",
        avatar: "/scribbles/doge.png",
        flag: "🇬🇧",
        badge: null,
        wins: 143,
        winsChange: "+16",
        winsUp: true,
        rekts: 67,
        rektsChange: null,
        rektsUp: null,
        challenges: 275,
        winRate: "76%",
        earnings: "94.3 SOL",
        isTop: false,
    },
    {
        rank: 5,
        username: "DiamondHands",
        avatar: "/scribbles/sol.png",
        flag: "🇪🇺",
        badge: null,
        wins: 131,
        winsChange: null,
        winsUp: null,
        rekts: 59,
        rektsChange: "-5",
        rektsUp: false,
        challenges: 265,
        winRate: "77%",
        earnings: "83.1 SOL",
        isTop: false,
    },
    {
        rank: 6,
        username: "Marinade",
        avatar: "/scribbles/coins.png",
        flag: "🇺🇸",
        badge: null,
        wins: 127,
        winsChange: null,
        winsUp: null,
        rekts: 70,
        rektsChange: "-9",
        rektsUp: false,
        challenges: 262,
        winRate: "75%",
        earnings: "72.5 SOL",
        isTop: false,
    },
    {
        rank: 7,
        username: "SolanaWhale",
        avatar: "/scribbles/sol.png",
        flag: "🇰🇷",
        badge: null,
        wins: 118,
        winsChange: "+12",
        winsUp: true,
        rekts: 52,
        rektsChange: "-4",
        rektsUp: false,
        challenges: 245,
        winRate: "74%",
        earnings: "68.3 SOL",
        isTop: false,
    },
    {
        rank: 8,
        username: "CryptoKing",
        avatar: "/scribbles/btc.png",
        flag: "🇬🇧",
        badge: null,
        wins: 112,
        winsChange: null,
        winsUp: null,
        rekts: 61,
        rektsChange: "-6",
        rektsUp: false,
        challenges: 238,
        winRate: "73%",
        earnings: "61.7 SOL",
        isTop: false,
    },
    {
        rank: 9,
        username: "PepeTrader",
        avatar: "/scribbles/pepe.png",
        flag: "🇨🇦",
        badge: null,
        wins: 105,
        winsChange: "+8",
        winsUp: true,
        rekts: 55,
        rektsChange: null,
        rektsUp: null,
        challenges: 220,
        winRate: "72%",
        earnings: "55.4 SOL",
        isTop: false,
    },
    {
        rank: 10,
        username: "DogeLover",
        avatar: "/scribbles/doge.png",
        flag: "🇪🇺",
        badge: null,
        wins: 98,
        winsChange: null,
        winsUp: null,
        rekts: 48,
        rektsChange: "-3",
        rektsUp: false,
        challenges: 205,
        winRate: "71%",
        earnings: "49.8 SOL",
        isTop: false,
    },
];

// Filter options
export const statusFilterOptions = ["Latest", "Expired", "Expiring Soon", "Ongoing", "Completed"];
export const modeFilterOptions = ["All Modes", "PVP", "Multi"];
