import { Clan } from "./ClanTypes";

export const clansData: Clan[] = [
    {
        rank: 1,
        name: "Alpha Syndicate",
        description: "Trade smart. Win together. Always stay one step ahead of the market.",
        leader: "LionKing",
        leaderAvatar: "/scribbles/btc.png",
        logo: "/scribbles/coins.png",
        type: "Public",
        members: 37,
        maxMembers: 50,
        totalWins: 128,
        totalRekts: 3460,
        winRate: 78,
        rektPoints: "12.4K",
        verified: true,
        chain: "Solana",
    },
    {
        rank: 2,
        name: "Rekt Hunters",
        description: "Hunt the markets. Rekt the rest.",
        leader: "Ragnar",
        leaderAvatar: "/scribbles/pepe.png",
        logo: "/scribbles/shiba.png",
        type: "Invite Only",
        members: 45,
        maxMembers: 50,
        totalWins: 96,
        totalRekts: 2780,
        winRate: 74,
        rektPoints: "9.8K",
        verified: true,
        chain: "Solana",
    },
    {
        rank: 3,
        name: "Market Mavericks",
        description: "Different mindset. Better results.",
        leader: "Maverick",
        leaderAvatar: "/scribbles/doge.png",
        logo: "/scribbles/btc.png",
        type: "Public",
        members: 31,
        maxMembers: 50,
        totalWins: 75,
        totalRekts: 2190,
        winRate: 71,
        rektPoints: "8.2K",
        verified: true,
        chain: "Ethereum",
    },
    {
        rank: 4,
        name: "Liquidity Legends",
        description: "Liquidity is power.",
        leader: "Aqua",
        leaderAvatar: "/scribbles/sol.png",
        logo: "/scribbles/dollars.png",
        type: "Invite Only",
        members: 27,
        maxMembers: 50,
        totalWins: 63,
        totalRekts: 1890,
        winRate: 68,
        rektPoints: "6.6K",
        verified: false,
        chain: "Solana",
    },
    {
        rank: 5,
        name: "Green Candles",
        description: "We don't guess, we predict.",
        leader: "Greeny",
        leaderAvatar: "/scribbles/pepe.png",
        logo: "/scribbles/bags.png",
        type: "Public",
        members: 23,
        maxMembers: 50,
        totalWins: 52,
        totalRekts: 1620,
        winRate: 65,
        rektPoints: "5.4K",
        verified: true,
        chain: "Ethereum",
    },
];